### ISSUE TITLE
Changing TTL Shutter State does not work as expected on TriggerScope 4

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/TriggerScopeMM#2]
TriggerScope 4 has two digital output devices, each controlling 8 TTL outputs. The TTL output can be controlled by (1) setting the State of the parent output device or (2) toggling the state of each output individually.

When the state of TTL-1 is changed to 1, the state of the parent output device is correctly changed to 1. When TTL-2 is also set to 1, the state of the parent output device is correctly changed to 3. When TTL-2 is then set to 0, the state of the parent output device is incorrectly set to 0. 

I would expect TTL-1 to remain ON, even if TTL-2 is turned off. In the above case, the state of the parent output device should be changed to 1 after TTL-2 is set to 0.

**Comment by nicost** [comment]
This is a logic bug in the device adapter code.  I'll push a fix there shortly.

**Comment by nicost** [comment]
Fixed in https://github.com/micro-manager/mmCoreAndDevices/pull/16.  Should be in tonight's build.

**Comment by ieivanov** [comment]
Thanks for your help @nicost. In this version of the device adapter, the TTL state logic is executed correctly, but the TTL output of the TriggerScope does not go high when the line state is changed in MicroManager. Could you please take another look at this?

**Comment by nicost** [comment]
Do you mean that the TTL state of 1-8 is set to 1, but TTL output number 1 does not go high?  Pretty sure I checked that on my Triggerscope (which is V3, so running different firmware).  Will check again.  I'll also have access to a V4 shortly so can fix that too if it does happen to be firmware.

Or do you mean that when you change the State directly, the TTL goes high, but not when you change TTL-1?

**Comment by ieivanov** [comment]
Both are true, if I remember correctly. Using the new device adapter I couldn't make the TTL lines go high in any way (either by changing the TTL 1-8 State or toggling individual lines). I also tested an older MM build and there the TTL states changed correctly, apart from the bug I reported above.

**Comment by nicost** [comment]
Thanks!  Should be fixed in tonight's build (PR #17 in mmCoreAndDevices repo).  Thanks for testing!

**Comment by ieivanov** [comment]
Thanks Nico, just tested and everything works well!
