### ISSUE TITLE
TTL Signal Delay with TriggerScope 4 does not work

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/TriggerScopeMM#3]
TTL outputs on TriggerScope 4 can be used as TTL shutters by linking the TriggerScope digital output device to a State Device Shutter. During setup of the config, a delay can be added to the State Device Shutter. Adding a delay to the State Device Shutter does not lead to delay of the TTL pulse relative to the camera trigger.

**Comment by nicost** [comment]
Do you mean the Delay that you set in the Hardware Configuration Wizard (page 4 or so)?  That delay is not use to delay the TTL changing state with a delay relative to the camera trigger, rather, it is used to report that device is Busy during the time set in the Delay page after changing its state.  See the section about "Busy" in https://github.com/micro-manager/futureMMCore/blob/main/MMCoreDesign.pdf.  I think that I understand what you are after (and even spend some time working on something like that).  It may best to open a new issue as a feature request.

**Comment by ieivanov** [comment]
Hi @nicost, yes, your understanding is correct.

This feature is not a priority for me, feel free to create a new feature request issue, and work on it as your time allows.

One interesting related feature may be to add a "negative delay" to the TTL shutter, such that, for example, a light source is triggered before the camera exposure during a sequenced acquisition. I realize this is hard to do, but let me know if you see any straightforward implementation.

**Comment by nicost** [comment]
Hi @ieivanov, I was working a while ago on adding in delays for both DACs and TTLs, but the party who wanted that feature lost interest.  It needs work on the firwmare side, not extremely difficult, but needs time to get right.  

I have no idea how to implement a negative delay, as the Triggerscope can not anticipate when the camera trigger will arrive.  In such a case, the camera probably should be run in external trigger mode, and the Triggerscope should provide the camera trigger.  Then it can activate the TTL shutter before sending the camera trigger.  Certainly something desirable, but not trivial to make something that still can be controller through properties in a reasonably understandable way.
