### ISSUE TITLE
TriggerScope 4 DAC control does not work as expected

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/TriggerScopeMM#4]
TriggerScope 4 provides 16 DAC output. The State and Voltage of each output can be set through MicroManager. 

When the State of a DAC output is 0 and Volts is changed to, e.g. 1 V, the line outputs 1V and the reported State in MM remains at 0. The expected behavior is that setting the voltage should not result in output on the line. The output should be toggles by the State property.

In addition, changing the State from 1 to 0 also changes the Voltage to 0. The voltage should remain at the pre-set value, such that at a later point the output device can be set to the same voltage when State is changed from 0 to 1.

@nicost we're happy to lend you our TriggerScope 4 for troubleshooting if you'd like.

**Comment by nicost** [comment]
Is this for the TroggerScope or TriggerScopeMM device adapter/firmware? Edit: Just noted where this was posted, which answers the question;)

**Comment by ieivanov** [comment]
Ah, sorry! All of the issues I posted are with the TriggerScopeMM device adapter and the v4 firmware from this repo. Good to clarify :)

**Comment by nicost** [comment]
Fixed in https://github.com/micro-manager/mmCoreAndDevices/pull/16. Should be in tonight's build.
