### ISSUE TITLE
DAC Sequencing does not work

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/TriggerScopeMM#6]
Sequenced acquisition based on the DAC State property does not work - the camera is not run in sequence mode (judging from the Exposure OUT signal). The acquisition is set up in the MM MDA window with two Channels (State = 0 and State = 1) and 50 time points with 0 s internal.

The same happens when DAC Volts is used to define channels (0V, 1V, 2V, etc.). Are both properties supposed to be sequenceable? That would certainly be nice. 

(note: sequencing based on TTL1-8-State works well)

**Comment by nicost** [comment]
Hi @ieivanov,  Sorry to be pedantic, but all these issue are issues with the device adapter code (https://github.com/micro-manager/mmCoreAndDevices), not with the Triggerscope Firmware (this repository).  Easier to keep them close to the code they pertain to.

Sequencing is implemented for the DA device representing the DAC.  I agree that it would be nice to have the Volt property aslo be sequenceable, and will implement that.  Not sure if the State property should also be sequenceable.  This is mainly supposed to be used as a shutter.  Having both OnVolt and onState be sequenceable could lead to interesting sequences being run at the same time, which may lead to very unexpected consequences.

**Comment by nicost** [comment]
Volt property was made Sequenceable: https://github.com/micro-manager/mmCoreAndDevices/pull/19.  

B.t.w., highly appreciate your testing and opening tickets!

**Comment by ieivanov** [comment]
Thanks Nico! This works nearly perfectly. Sequencing based on the Volts property works, but setting Sequence Trigger Edge to Falling has no effect - the triggering still happens on the positive edge. Could you please look into that too (I think that would be our main application)? Happy to create another ticket under mmCoreAndDevices, if you'd like.

Sorry for the confusion on where I created the tickets. It wasn't clear to me if the issues stemmed from the firmware or device adapter. I'll create future tickets under mmCoreAndDevices. 

Thanks again for troubleshooting this with me. This is exactly what we need for our application.
